install:
- true

script:
- set -e
- ./gradlew check --info --stacktrace --continue -Pcoverage -Pcompatibility
- source build/release/gradle/setGitVariables.sh
- ./gradlew release -Prelease.disableRemoteCheck -Prelease.localOnly --info --stacktrace
- ./gradlew finalizeRelease publishUploadedArtifacts -PbintrayUser=${BINTRAY_USER} -PbintrayKey=${BINTRAY_API_KEY} --info --stacktrace

language: java

jdk:
- oraclejdk8
    
env:
  global:
  - secure: O+abvfmpkYYinROSccqOPqCTOD/6gNxtV1fZyrH56yaAnDghHH79vhD9UNRRMTyAmFsOLA9gGczJ5DW7pPucfSHfoydlnzfU8FWLWNLWSIsCwm1nvWRGmqJkKdS5vXoJLuRb3vgAq19bspnV+0UrrfZogBhXKhZV3TWRPkG3Zt1IxZFX2PfhzYMTM6ITX/t449uFpP/jqan5utfdmvxMruWpFkTVbtZ8LmBnoD47myx0l/0UbVEyodNqZSt3vtIN6TaU6MrXNO96iXFNC3yEyqc0288cLamOOAtIT6x+hFoRvC5yE+NgjcJm+16pteABn3KQHlPfFjxkWfYj9PEwYz6OQXQcmqq+ml63tle7HtWekev/xBcJ6a4nxHG46+53Out9ejzZPQVcilaqW+PwLZXkKOL5pFCEQ+bCxsPadRlYmg30aHb6dA4L0/tNIcErxvlXZaLOhO+TXfAftPC1vrI/ObNyk9TDYtImvnopLGuToV1+q3GoDEsT9rETXJHBvRwnTz3Xo/we4hJT3PG0LAZQAzxxbQufkdE0Dikw3TF0uwaKAiy//C/FPH+ohF4ISKhM8NKVYxCTHw/T/oBnSbVpQqfbVfZ5WebHe4Otd7lvgREwWhjIH6DNygoPDHkeiFUdKNwTEaBHOgiqWNsBJHCvvlwEDgjmoDN02/BQCGc=
  - secure: xW3yb/qfiICyPEeJZoEZnvpEBy0FmbgeOImFATFXSEflsSaA5K+A45iGbb34OheFN1X7p+L7ajtW3367bIt3QV1WH+ZvSxMznBKpEI3lVN+50c0x54qn1oaTLF776FK8g1DfFnrnUTYr4Z9KBkSWQR6o3+JPWYc+haXERjjsQmUt1fOAw0TvCzBSr2L/i6k2XLSv30NBoNCt+F99qZXMqQhRqdd6h4YJCMHgKgzm0EWfmPR0XT+WIYXPy5sMVHzRDviE/fs8w0JKD6PpBnmbQFB6o3eCNqPR++sNS49GKHpPukIyWRKAy1GENT8/KERgjLV/vry76zdr9r2IV8nQKzGTgG0pSYvRLNJfGT/HLaixvLUv2J926hl+r0nG8M4I46ZfMwlwSfqSrtrs3UaLvyDSa5+ZG0dRDX+1yC+YbQWwtCBxKr9vnkWtL06WvfCy7p0DOm4lRWjyKzumaAgNe3OTOtZbEKMEbdtwkL3IHFPeUczDiLXiJVxXpBgAQbebPaVs1k2Walc+GDLjUBK+Gl6G863bfW+SjVWK1Q2cIvht6DAoFRAO1t5KTCxLf7ouURnThHtGH3uxJZ19IaXmDkgAZMLF+LfG6ZU7Oc7w66SHrPYe95JC3Badxe78A1jBvCMejr29vIatx8s4NhPeR3gpsGdow9J2m7lIw3QE2eo=